/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.228, 3.058, -0.007]} rotation={[0, 0.256, 0]} scale={0.627}>
        <group position={[0.028, -0.12, -0.091]} rotation={[0.061, -0.037, -0.024]}>
          <group position={[0, 0.605, 0]} rotation={[-0.043, 0.034, 0.048]}>
            <group position={[0, 2.932, 0]} rotation={[-0.026, 0.003, -0.144]}>
              <group position={[0, 0.277, 0]} rotation={[0.006, 0, 0.141]}>
                <mesh geometry={nodes.Cube003.geometry} material={materials['Material.001']} position={[0.009, 0.693, 0.011]} rotation={[0.001, 0, -0.019]} scale={[-0.923, -0.72, -0.494]} />
                <mesh geometry={nodes.Cube008.geometry} material={materials['Material.039']} position={[-0.02, 0.356, 0.52]} rotation={[-3.141, 0, 0.019]} scale={[-0.527, -0.109, -0.016]} />
                <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.031']} position={[-0.434, 0.922, 0.568]} rotation={[1.562, -0.019, 0]} scale={[-0.213, -0.019, -0.213]} />
                <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.034']} position={[0.434, 0.906, 0.568]} rotation={[1.562, -0.019, 0]} scale={[-0.213, -0.019, -0.213]} />
                <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Material.020']} position={[1.037, 1.335, 0.017]} rotation={[0.02, 0.046, -0.087]} scale={[0.026, 0.372, 0.019]} />
                <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.021']} position={[-0.989, 1.372, 0.017]} rotation={[0.01, -0.005, 0.017]} scale={[0.026, 0.372, 0.019]} />
                <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.038']} position={[-1.072, 0.807, 0.025]} rotation={[0.001, 0, -1.575]} scale={[0.236, 0.053, 0.236]} />
                <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.036']} position={[1.09, 0.766, 0.016]} rotation={[0.001, 0, -1.575]} scale={[0.236, 0.053, 0.236]} />
                <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.035']} position={[0.986, 0.751, 0.011]} rotation={[0.001, 0, -1.575]} scale={[0.337, 0.062, 0.337]} />
                <mesh geometry={nodes.Cylinder012.geometry} material={materials['Material.037']} position={[-0.963, 0.788, 0.011]} rotation={[0.001, 0, -1.575]} scale={[0.337, 0.062, 0.337]} />
                <mesh geometry={nodes.Plane.geometry} material={materials['Material.030']} position={[-1, -2.286, 1.769]} rotation={[1.571, -0.019, 0]} scale={1.596} />
                <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.018']} position={[1.075, 1.765, 0.039]} rotation={[0.001, 0, -0.019]} scale={-0.09} />
                <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.019']} position={[-1.009, 1.803, 0.039]} rotation={[0.001, 0, -0.019]} scale={-0.09} />
              </group>
            </group>
            <group position={[0.142, 2.945, -0.014]} rotation={[-0.047, 0.051, -2.031]}>
              <group position={[0, 1.732, 0]} rotation={[-0.019, 0.007, -0.903]}>
                <group position={[0, 1.702, 0]} rotation={[-0.039, 0.011, -0.284]}>
                  <group position={[0, 1.338, 0]} rotation={[0.041, -0.011, -0.019]}>
                    <mesh geometry={nodes.Cube013_1.geometry} material={materials['Material.011']} position={[3.851, 0.429, -0.261]} rotation={[-1.584, -0.111, -1.512]} scale={[0.287, 0.251, 0.576]} />
                  </group>
                  <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.007']} position={[0.042, 0.536, -0.001]} rotation={[0.022, 0.062, 0.053]} scale={[-0.432, -0.699, -0.508]} />
                </group>
                <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[0.094, 0.004, 0.041]} rotation={[-0.001, 0.062, -1.799]} scale={[0.246, 0.274, 0.246]} />
                <mesh geometry={nodes.Cylinder013.geometry} material={materials['Material.005']} position={[-0.275, 0.141, 0.052]} rotation={[-3.136, -0.089, 1.799]} scale={[0.6, 0.381, 0.6]} />
                <mesh geometry={nodes.Cylinder015.geometry} material={materials['Material.006']} position={[-0.016, 1.122, 0.017]} rotation={[0, 0.065, 2.913]} scale={[0.236, 0.968, 0.202]} />
              </group>
            </group>
            <group position={[-0.065, 2.972, 0.001]} rotation={[-0.049, -0.042, 2.012]}>
              <group position={[0, 1.761, 0]} rotation={[-0.116, 0.047, 0.909]}>
                <group position={[0, 1.78, 0]} rotation={[-0.031, -0.002, 0.191]}>
                  <group position={[0, 1.213, 0]} rotation={[-0.051, 0.016, 0.067]}>
                    <mesh geometry={nodes.Cube014_1.geometry} material={materials['Material.011']} position={[0.007, 0.177, -0.004]} rotation={[-1.513, 0.04, -1.779]} scale={[0.287, 0.251, 0.576]} />
                  </group>
                  <mesh geometry={nodes.Cube.geometry} material={materials['Material.009']} position={[-0.066, 0.453, 0.006]} rotation={[0.013, -0.173, -0.013]} scale={[-0.432, -0.699, -0.508]} />
                </group>
                <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.008']} position={[0.314, 0.114, 0.094]} rotation={[0.015, -0.17, -1.371]} scale={[0.6, 0.381, 0.6]} />
                <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-0.04, -0.011, -0.004]} rotation={[-3.121, 0.197, 1.369]} scale={[0.246, 0.274, 0.246]} />
                <mesh geometry={nodes.Cylinder014.geometry} material={materials['Material.010']} position={[0.041, 1.085, 0.009]} rotation={[0.015, -0.17, -2.941]} scale={[0.236, 0.522, 0.202]} />
              </group>
            </group>
            <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-0.027, 1.48, 0.037]} rotation={[-0.018, 0.062, 3.12]} scale={[-1.409, -1.409, -0.684]} />
            <mesh geometry={nodes.Cube015.geometry} material={materials['Material.025']} position={[0.006, 1.45, 0.745]} rotation={[3.124, -0.062, -3.12]} scale={[-1.156, -0.804, -0.034]} />
            <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.028']} position={[0.799, 1.748, 0.747]} rotation={[-1.562, 0.023, 0.062]} scale={[0.224, 0.05, 0.224]} />
            <mesh geometry={nodes.Cylinder020.geometry} material={materials['Material.029']} position={[0.783, 1.019, 0.761]} rotation={[-1.562, 0.023, 0.062]} scale={[0.224, 0.05, 0.224]} />
            <mesh geometry={nodes.Cylinder021.geometry} material={materials['Material.026']} position={[0.803, 1.75, 0.824]} rotation={[-1.562, 0.023, 0.062]} scale={[0.173, 0.039, 0.173]} />
            <mesh geometry={nodes.Cylinder022.geometry} material={materials['Material.027']} position={[0.788, 1.022, 0.838]} rotation={[-1.562, 0.023, 0.062]} scale={[0.173, 0.039, 0.173]} />
          </group>
          <group position={[0.763, 0.157, 0.031]} rotation={[-0.252, 0.47, -3.121]}>
            <group position={[0, 0.633, 0]} rotation={[-0.249, 0.068, 0.098]}>
              <mesh geometry={nodes.Cube005.geometry} material={materials['Material.004']} position={[0.006, 1.294, -0.13]} rotation={[0.121, 0.249, -0.021]} scale={[-0.447, -1.291, -0.523]} />
              <mesh geometry={nodes.Cube010.geometry} material={materials['Material.014']} position={[-0.02, 2.116, -0.057]} rotation={[0.121, 0.271, 3.124]} scale={[0.587, 0.329, 0.69]} />
              <mesh geometry={nodes.Cube011.geometry} material={materials['Material.016']} position={[0.019, 2.564, -0.004]} rotation={[0.121, 0.249, 3.124]} scale={[0.739, 0.091, 0.768]} />
            </group>
            <mesh geometry={nodes.Cylinder017.geometry} material={materials['Material.012']} position={[-0.023, 0.313, -0.227]} rotation={[-0.23, 0.678, -2.989]} scale={[-0.308, -0.475, -0.263]} />
          </group>
          <mesh geometry={nodes.Cube004.geometry} material={materials['Material.022']} position={[0.019, 0.492, 0.036]} rotation={[-0.065, 0.177, 0.027]} scale={[1.12, 0.243, 0.504]} />
        </group>
        <group position={[-0.698, 0.046, 0.178]} rotation={[-3.118, -0.65, 0.089]}>
          <group position={[0, 0.645, 0]} rotation={[0.047, -0.004, -0.09]}>
            <mesh geometry={nodes.Cube006.geometry} material={materials['Material.003']} position={[0.09, 1.291, -0.014]} rotation={[3.046, -0.737, 3.065]} scale={[-0.447, -1.291, -0.523]} />
            <mesh geometry={nodes.Cube007.geometry} material={materials['Material.017']} position={[0.022, 2.565, -0.05]} rotation={[3.046, -0.737, -0.072]} scale={[0.739, 0.091, 0.768]} />
            <mesh geometry={nodes.Cube009.geometry} material={materials['Material.015']} position={[0.049, 2.243, -0.033]} rotation={[3.046, -0.737, -0.072]} scale={[0.587, 0.329, 0.69]} />
          </group>
          <mesh geometry={nodes.Cylinder016.geometry} material={materials['Material.013']} position={[0.104, 0.313, 0.049]} rotation={[-3.135, -0.925, 0.1]} scale={[-0.308, -0.475, -0.263]} />
        </group>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.024']} position={[-0.031, 3.598, 0.003]} scale={[-0.297, -0.111, -0.37]} />
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Material.023']} position={[-0.031, 3.383, 0.003]} scale={[-0.389, -0.145, -0.486]} />
      </group>
    </group>
  )
}

useGLTF.preload('/Untitled.glb')
